=== GeorgeXie2333/vpngate-list-mirror/schemas/pool/v1/config.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "VPN Gate pool v1 config",
  "type": "object",
  "required": [
    "kind",
    "schema_version",
    "openvpn_config_base64",
    "openvpn_config_sha256",
    "openvpn_config_bytes"
  ],
  "properties": {
    "kind": {
      "const": "vpngate-pool-config"
    },
    "schema_version": {
      "const": 1
    },
    "openvpn_config_base64": {
      "type": "string",
      "minLength": 4,
      "maxLength": 174764,
      "contentEncoding": "base64"
    },
    "openvpn_config_sha256": {
      "type": "string",
      "pattern": "^[0-9a-f]{64}$"
    },
    "openvpn_config_bytes": {
      "type": "integer",
      "minimum": 1,
      "maximum": 131072
    }
  },
  "additionalProperties": true
}

=== GeorgeXie2333/vpngate-list-mirror/pool/configs/5be8d129871cb4d30e015fe8901a1d68be1e79dd01aa99a8500675c3c6daee4a.json
{
  "kind": "vpngate-pool-config",
  "openvpn_config_base64": "IyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIw0KIyBPcGVuVlBOIDIuMCBTYW1wbGUgQ29uZmlndXJhdGlvbiBGaWxlDQojIGZvciBQYWNrZXRpWCBWUE4gLyBTb2Z0RXRoZXIgVlBOIFNlcnZlcg0KIyANCiMgISEhIEFVVE8tR0VORVJBVEVEIEJZIFNPRlRFVEhFUiBWUE4gU0VSVkVSIE1BTkFHRU1FTlQgVE9PTCAhISENCiMgDQojICEhISBZT1UgSEFWRSBUTyBSRVZJRVcgSVQgQkVGT1JFIFVTRSBBTkQgTU9ESUZZIElUIEFTIE5FQ0VTU0FSWSAhISENCiMgDQojIFRoaXMgY29uZmlndXJhdGlvbiBmaWxlIGlzIGF1dG8tZ2VuZXJhdGVkLiBZb3UgbWlnaHQgdXNlIHRoaXMgY29uZmlnIGZpbGUNCiMgaW4gb3JkZXIgdG8gY29ubmVjdCB0byB0aGUgUGFja2V0aVggVlBOIC8gU29mdEV0aGVyIFZQTiBTZXJ2ZXIuDQojIEhvd2V2ZXIsIGJlZm9yZSB5b3UgdHJ5IGl0LCB5b3Ugc2hvdWxkIHJldmlldyB0aGUgZGVzY3JpcHRpb25zIG9mIHRoZSBmaWxlDQojIHRvIGRldGVybWluZSB0aGUgbmVjZXNzaXR5IHRvIG1vZGlmeSB0byBzdWl0YWJsZSBmb3IgeW91ciByZWFsIGVudmlyb25tZW50Lg0KIyBJZiBuZWNlc3NhcnksIHlvdSBoYXZlIHRvIG1vZGlmeSBhIGxpdHRsZSBhZGVxdWF0ZWx5IG9uIHRoZSBmaWxlLg0KIyBGb3IgZXhhbXBsZSwgdGhlIElQIGFkZHJlc3Mgb3IgdGhlIGhvc3RuYW1lIGFzIGEgZGVzdGluYXRpb24gVlBOIFNlcnZlcg0KIyBzaG91bGQgYmUgY29uZmlybWVkLg0KIyANCiMgTm90ZSB0aGF0IHRvIHVzZSBPcGVuVlBOIDIuMCwgeW91IGhhdmUgdG8gcHV0IHRoZSBjZXJ0aWZpY2F0aW9uIGZpbGUgb2YNCiMgdGhlIGRlc3RpbmF0aW9uIFZQTiBTZXJ2ZXIgb24gdGhlIE9wZW5WUE4gQ2xpZW50IGNvbXB1dGVyIHdoZW4geW91IHVzZSB0aGlzDQojIGNvbmZpZyBmaWxlLiBQbGVhc2UgcmVmZXIgdGhlIGJlbG93IGRlc2NyaXB0aW9ucyBjYXJlZnVsbHkuDQoNCg0KIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIw0KIyBTcGVjaWZ5IHRoZSB0eXBlIG9mIHRoZSBsYXllciBvZiB0aGUgVlBOIGNvbm5lY3Rpb24uDQojIA0KIyBUbyBjb25uZWN0IHRvIHRoZSBWUE4gU2VydmVyIGFzIGEgIlJlbW90ZS1BY2Nlc3MgVlBOIENsaWVudCBQQyIsDQojICBzcGVjaWZ5ICdkZXYgdHVuJy4gKExheWVyLTMgSVAgUm91dGluZyBNb2RlKQ0KIw0KIyBUbyBjb25uZWN0IHRvIHRoZSBWUE4gU2VydmVyIGFzIGEgYnJpZGdpbmcgZXF1aXBtZW50IG9mICJTaXRlLXRvLVNpdGUgVlBOIiwNCiMgIHNwZWNpZnkgJ2RldiB0YXAnLiAoTGF5ZXItMiBFdGhlcm5ldCBCcmlkZ2luZSBNb2RlKQ0KDQpkZXYgdHVuDQoNCg0KIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIw0KIyBTcGVjaWZ5IHRoZSB1bmRlcmx5aW5nIHByb3RvY29sIGJleW9uZCB0aGUgSW50ZXJuZXQuDQojIE5vdGUgdGhhdCB0aGlzIHNldHRpbmcgbXVzdCBiZSBjb3JyZXNwb25kIHdpdGggdGhlIGxpc3RlbmluZyBzZXR0aW5nIG9uDQojIHRoZSBWUE4gU2VydmVyLg0KIyANCiMgU3BlY2lmeSBlaXRoZXIgJ3Byb3RvIHRjcCcgb3IgJ3Byb3RvIHVkcCcuDQoNCnByb3RvIHRjcA0KDQoNCiMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMNCiMgVGhlIGRlc3RpbmF0aW9uIGhvc3RuYW1lIC8gSVAgYWRkcmVzcywgYW5kIHBvcnQgbnVtYmVyIG9mDQojIHRoZSB0YXJnZXQgVlBOIFNlcnZlci4NCiMgDQojIFlvdSBoYXZlIHRvIHNwZWNpZnkgYXMgJ3JlbW90ZSA8SE9TVE5BTUU+IDxQT1JUPicuIFlvdSBjYW4gYWxzbw0KIyBzcGVjaWZ5IHRoZSBJUCBhZGRyZXNzIGluc3RlYWQgb2YgdGhlIGhvc3RuYW1lLg0KIyANCiMgTm90ZSB0aGF0IHRoZSBhdXRvLWdlbmVyYXRlZCBiZWxvdyBob3N0bmFtZSBhcmUgYSAiYXV0by1kZXRlY3RlZA0KIyBJUCBhZGRyZXNzIiBvZiB0aGUgVlBOIFNlcnZlci4gWW91IGhhdmUgdG8gY29uZmlybSB0aGUgY29ycmVjdG5lc3MNCiMgYmVmb3JlaGFuZC4NCiMgDQojIFdoZW4geW91IHdhbnQgdG8gY29ubmVjdCB0byB0aGUgVlBOIFNlcnZlciBieSB1c2luZyBUQ1AgcHJvdG9jb2wsDQojIHRoZSBwb3J0IG51bWJlciBvZiB0aGUgZGVzdGluYXRpb24gVENQIHBvcnQgc2hvdWxkIGJlIHNhbWUgYXMgb25lIG9mDQojIHRoZSBhdmFpbGFibGUgVENQIGxpc3RlbmVycyBvbiB0aGUgVlBOIFNlcnZlci4NCiMgDQojIFdoZW4geW91IHVzZSBVRFAgcHJvdG9jb2wsIHRoZSBwb3J0IG51bWJlciBtdXN0IHNhbWUgYXMgdGhlIGNvbmZpZ3VyYXRpb24NCiMgc2V0dGluZyBvZiAiT3BlblZQTiBTZXJ2ZXIgQ29tcGF0aWJsZSBGdW5jdGlvbiIgb24gdGhlIFZQTiBTZXJ2ZXIuDQoNCnJlbW90ZSAyMTguMTQ2Ljc0LjE4NCA5OTUNCg0KDQojIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjDQojIFRoZSBIVFRQL0hUVFBTIHByb3h5IHNldHRpbmcuDQojIA0KIyBPbmx5IGlmIHlvdSBoYXZlIHRvIHVzZSB0aGUgSW50ZXJuZXQgdmlhIGEgcHJveHksIHVuY29tbWVudCB0aGUgYmVsb3cNCiMgdHdvIGxpbmVzIGFuZCBzcGVjaWZ5IHRoZSBwcm94eSBhZGRyZXNzIGFuZCB0aGUgcG9ydCBudW1iZXIuDQojIEluIHRoZSBjYXNlIG9mIHVzaW5nIHByb3h5LWF1dGhlbnRpY2F0aW9uLCByZWZlciB0aGUgT3BlblZQTiBtYW51YWwuDQoNCjtodHRwLXByb3h5LXJldHJ5DQo7aHR0cC1wcm94eSBbcHJveHkgc2VydmVyXSBbcHJveHkgcG9ydF0NCg0KDQojIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjDQojIFRoZSBlbmNyeXB0aW9uIGFuZCBhdXRoZW50aWNhdGlvbiBhbGdvcml0aG0uDQojIA0KIyBEZWZhdWx0IHNldHRpbmcgaXMgZ29vZC4gTW9kaWZ5IGl0IGFzIHlvdSBwcmVmZXIuDQojIFdoZW4geW91IHNwZWNpZnkgYW4gdW5zdXBwb3J0ZWQgYWxnb3JpdGhtLCB0aGUgZXJyb3Igd2lsbCBvY2N1ci4NCiMgDQojIFRoZSBzdXBwb3J0ZWQgYWxnb3JpdGhtcyBhcmUgYXMgZm9sbG93czoNCiMgIGNpcGhlcjogW05VTEwtQ0lQSEVSXSBOVUxMIEFFUy0xMjgtQ0JDIEFFUy0xOTItQ0JDIEFFUy0yNTYtQ0JDIEJGLUNCQw0KIyAgICAgICAgICBDQVNULUNCQyBDQVNUNS1DQkMgREVTLUNCQyBERVMtRURFLUNCQyBERVMtRURFMy1DQkMgREVTWC1DQkMNCiMgICAgICAgICAgUkMyLTQwLUNCQyBSQzItNjQtQ0JDIFJDMi1DQkMgQ0FNRUxMSUEtMTI4LUNCQyBDQU1FTExJQS0xOTItQ0JDIENBTUVMTElBLTI1Ni1DQkMNCiMgIGRhdGEtY2lwaGVyczogc2FtZSBhcyBjaXBoZXINCiMgIGF1dGg6ICAgU0hBIFNIQTEgU0hBMjU2IFNIQTM4NCBTSEE1MTIgTUQ1IE1ENCBSTUQxNjANCiMNCiMgTm90ZTogVG8gc29sdmUgT3BlblZQTiBjb21wYXRpYmlsaXR5IGJ1Zw0KIyBSZWNlbnQgdmVyc2lvbnMgb2YgdGhlIE9wZW5WUE4gYXBwIHJlcXVpcmUgc3BlY2lmeWluZyB0aGUgImRhdGEtY2lwaGVycyINCiMgZmllbGQgaW5zdGVhZCBvZiB0aGUgImNpcGhlciIgZmllbGQuIEhvd2V2ZXIsIG9sZGVyIHZlcnNpb25zIG9mIHRoZSBPcGVuVlBOIGFwcA0KIyBkbyBub3QgcmVjb2duaXplICJkYXRhLWNpcGhlcnMuIiBSYXRoZXIgdGhhbiBpZ25vcmluZyBpdCwgdGhleSBwcm9kdWNlDQojIGEgc3RhcnR1cCBlcnJvciBzdGF0aW5nIHRoYXQgIm5vIHN1Y2ggb3B0aW9uIGV4aXN0cy4iIFRoaXMgaXMgYSBidWcNCiMgaW4gT3BlblZQTi4gSWYgeW91IGVuY291bnRlciB0aGlzIGlzc3VlLCBwbGVhc2UgY29tbWVudCBvdXQNCiMgdGhlICJkYXRhLWNpcGhlcnMiIGxpbmUuDQoNCmNpcGhlciBBRVMtMTI4LUNCQw0KZGF0YS1jaXBoZXJzIEFFUy0xMjgtQ0JDDQphdXRoIFNIQTENCg0KDQojIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjDQojIE90aGVyIHBhcmFtZXRlcnMgbmVjZXNzYXJ5IHRvIGNvbm5lY3QgdG8gdGhlIFZQTiBTZXJ2ZXIuDQojIA0KIyBJdCBpcyBub3QgcmVjb21tZW5kZWQgdG8gbW9kaWZ5IGl0IHVubGVzcyB5b3UgaGF2ZSBhIHBhcnRpY3VsYXIgbmVlZC4NCg0KcmVzb2x2LXJldHJ5IGluZmluaXRlDQpub2JpbmQNCnBlcnNpc3Qta2V5DQpwZXJzaXN0LXR1bg0KY2xpZW50DQp2ZXJiIDMNCiNhdXRoLXVzZXItcGFzcw0KDQoNCiMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMNCiMgVGhlIGNlcnRpZmljYXRlIGZpbGUgb2YgdGhlIGRlc3RpbmF0aW9uIFZQTiBTZXJ2ZXIuDQojIA0KIyBUaGUgQ0EgY2VydGlmaWNhdGUgZmlsZSBpcyBlbWJlZGRlZCBpbiB0aGUgaW5saW5lIGZvcm1hdC4NCiMgWW91IGNhbiByZXBsYWNlIHRoaXMgQ0EgY29udGVudHMgaWYgbmVjZXNzYXJ5Lg0KIyBQbGVhc2Ugbm90ZSB0aGF0IGlmIHRoZSBzZXJ2ZXIgY2VydGlmaWNhdGUgaXMgbm90IGEgc2VsZi1zaWduZWQsIHlvdSBoYXZlIHRvDQojIHNwZWNpZnkgdGhlIHNpZ25lcidzIHJvb3QgY2VydGlmaWNhdGUgKENBKSBoZXJlLg0KDQo8Y2E+DQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0NCk1JSUZhekNDQTFPZ0F3SUJBZ0lSQUlJUXo3RFNRT05aUkdQZ3UyT0Npd0F3RFFZSktvWklodmNOQVFFTEJRQXcNClR6RUxNQWtHQTFVRUJoTUNWVk14S1RBbkJnTlZCQW9USUVsdWRHVnlibVYwSUZObFkzVnlhWFI1SUZKbGMyVmgNCmNtTm9JRWR5YjNWd01SVXdFd1lEVlFRREV3eEpVMUpISUZKdmIzUWdXREV3SGhjTk1UVXdOakEwTVRFd05ETTQNCldoY05NelV3TmpBME1URXdORE00V2pCUE1Rc3dDUVlEVlFRR0V3SlZVekVwTUNjR0ExVUVDaE1nU1c1MFpYSnUNClpYUWdVMlZqZFhKcGRIa2dVbVZ6WldGeVkyZ2dSM0p2ZFhBeEZUQVRCZ05WQkFNVERFbFRVa2NnVW05dmRDQlkNCk1UQ0NBaUl3RFFZSktvWklodmNOQVFFQkJRQURnZ0lQQURDQ0Fnb0NnZ0lCQUszb0pIUDBGRGZ6bTU0clZ5Z2MNCmg3N2N0OTg0a0l4dVBPWlhvSGozZGNLaS92VnFidllBVHlqYjNtaUdiRVNUdHJGai9SUVNhNzhmMHVveG15RisNCjBUTTh1a2oxM1huZnM3ai9FdkVobWt2QmlvWnhhVXBtWm15UGZqeHd2NjBwSWdiejVNRG1nSzdpUzQrM21YNlUNCkE1L1RSNWQ4bVVnalUrZzRyazhLYjRNdTBVbFhqSUIwdHRvdjBEaU5ld053SVJ0MThqQTgrbyt1M2RwanErc1cNClQ4S09FVXQrend2by83VjNMdlN5ZTByZ1RCSWxESENOQXltZzRWTWs3QlBaN2htL0VMTktqRCtKbzJGUjNxeUgNCkI1VDBZM0hzTHVKdlc1aUI0WWxjTkhsc2R1ODdrR0o1NXR1a21pOG14ZEFRNFE3ZTJSQ09GdnUzOTZqM3grVUMNCkI1aVBOZ2lWNStJM2xnMDJkWjc3RG5LeEhadThBL2xKQmRpQjNRVzBLdFpCNmF3QmRwVUtEOWpmMWIwU0h6VXYNCktCZHMwcGpCcUFsa2QyNUhON3JPckZsZWFKMS9jdGFKeFFaQktUNVpQdDBtOVNUSkVhZGFvMHhBSDBhaG1iV24NCk9sRnVoanVlZlhLbkVnVjRXZTArVVhnVkN3T1BqZEF2QmJJK2Uwb2NTM01GRXZ6RzZ1QlFFM3hEazNTenluVG4NCmpoOEJDTkF3MUZ0eE5yUUh1c0V3TUZ4SXQ0STdtS1o5WUlxaW95bUN6THE5Z3dRYm9vTURRYUhXQmZFYndyYncNCnFIeUdPMGFvU0NxSTNIYWFkcjhmYXFVOUdZL3JPUE5rM3NnckRRb28vL2ZiNGhWQzFDTFFKMTNoZWY0WTUzQ0kNCnJVN20yWXM2eHQwblVXNy92R1QxTTBOUEFnTUJBQUdqUWpCQU1BNEdBMVVkRHdFQi93UUVBd0lCQmpBUEJnTlYNCkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlI1dEZubWU3Ymw1QUZ6Z0FpSXlCcFk5dW1iYmpBTkJna3ENCmhraUc5dzBCQVFzRkFBT0NBZ0VBVlI5WXFieXlxRkRRRExIWUdta2dKeWtJckdGMVhJcHUrSUxsYVMvVjlsWkwNCnViaHpFRm5USVpkKzUweHgrN0xTWUswNXFBdnFGeUZXaGZGUURsbnJ6dUJaNmJySkZlK0duWStFZ1BiazZaR1ENCjNCZWJZaHRGOEdhVjBueHZ3dW83N3gvUHk5YXVKL0dwc01pdS9YMSttdm9pQk92LzJYL3FrU3Npc1JjT2ovS0sNCk5GdFkyUHdCeVZTNXVDYk1pb2d6aVV3dGhEeUMzKzZXVndXNkxMdjN4TGZIVGp1Q3ZqSElJbk56a3RIQ2dLUTUNCk9SQXpJNEpNUEorR3NsV1lIYjRwaG93aW01N2lhenRYT29Kd1Rkd0p4NG5MQ2dkTmJPaGRqc252enF2SHU3VXINClRrWFdTdEFtek9WeXlnaHFwWlhqRmFIM3BPM0pMRitsKy8rc0tBSXV2dGQ3dStOeGU1QVcwd2RlUmxOOE53ZEMNCmpOUEVscHpWbWJVcTRKVWFnRWl1VERrSHpzeEhwRktWSzdxNCs2M1NNMU45NVIxTmJkV2hzY2RDYitaQUp6VmMNCm95aTNCNDNualRPUTV5T2YrMUNjZVd4RzFiUVZzNVp1ZnBzTWxqcTRVaTAvMWx2aCt3akNoUDRrcUtPSjJxeHENCjRSZ3FzYWhEWVZ2VEg5dzdqWGJ5TGVpTmRkOFhNMnc5VS90N3kwRmYvOXlpMEdFNDRaYTRyRjJMTjlkMTFUUEENCm1SR3VuVUhCY25XRXZnSkJRbDluSkVpVTBac252Z2MvdWJoUGdYUlI0WHEzN1owajRyN2cxU2dFRXp3eEE1N2QNCmVteVB4Z2NZeG4vZVI0NC9LSjRFQnMrbFZEUjN2ZXlKbStrWFE5OWIyMS8ramg1WG9zMUFuWDVpSXRyZUdDYz0NCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0NCg0KPC9jYT4NCg0KDQojIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjDQojIFRoZSBjbGllbnQgY2VydGlmaWNhdGUgZmlsZSAoZHVtbXkpLg0KIyANCiMgSW4gc29tZSBpbXBsZW1lbnRhdGlvbnMgb2YgT3BlblZQTiBDbGllbnQgc29mdHdhcmUNCiMgKGZvciBleGFtcGxlOiBPcGVuVlBOIENsaWVudCBmb3IgaU9TKSwNCiMgYSBwYWlyIG9mIGNsaWVudCBjZXJ0aWZpY2F0ZSBhbmQgcHJpdmF0ZSBrZXkgbXVzdCBiZSBpbmNsdWRlZCBvbiB0aGUNCiMgY29uZmlndXJhdGlvbiBmaWxlIGR1ZSB0byB0aGUgbGltaXRhdGlvbiBvZiB0aGUgY2xpZW50Lg0KIyBTbyB0aGlzIHNhbXBsZSBjb25maWd1cmF0aW9uIGZpbGUgaGFzIGEgZHVtbXkgcGFpciBvZiBjbGllbnQgY2VydGlmaWNhdGUNCiMgYW5kIHByaXZhdGUga2V5IGFzIGZvbGxvd3MuDQoNCjxjZXJ0Pg0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlDeGpDQ0FhNENBUUF3RFFZSktvWklodmNOQVFFRkJRQXdLVEVhTUJnR0ExVUVBeE1SVmxCT1IyRjBaVU5zDQphV1Z1ZEVObGNuUXhDekFKQmdOVkJBWVRBa3BRTUI0WERURXpNREl4TVRBek5EazBPVm9YRFRNM01ERXhPVEF6DQpNVFF3TjFvd0tURWFNQmdHQTFVRUF4TVJWbEJPUjJGMFpVTnNhV1Z1ZEVObGNuUXhDekFKQmdOVkJBWVRBa
